services:
    web:
      build:
        context: web
      environment:
        - DATABASE_URL
        - NEXTAUTH_SECRET
        - NEXTAUTH_URL
        - AUTH_TRUST_HOST
        - STORAGE_S3_REGION
        - STORAGE_S3_KEY
        - STORAGE_S3_SECRET
        - STORAGE_S3_BUCKET
        - STORAGE_S3_ROOT
      restart: unless-stopped

    nginx:
      image: nginx:1-alpine
      ports:
        - "80:80"
      depends_on:
        - web
      volumes:
        - "./server/nginx.conf:/etc/nginx/nginx.conf:ro"
      restart: unless-stopped
